const cardData = [
  {
    id: 1,
    title: "Diabetes Test",
    price: 350,
    priceBefore: 700,
    type: "popularTests",
  },
  {
    id: 2,
    title: "Liquid Profile",
    price: 350,
    priceBefore: 700,
    type: "popularTests",
  },
  {
    id: 3,
    title: "Complete Blood Count",
    price: 240,
    priceBefore: 300,
    type: "popularTests",
  },
  {
    id: 4,
    title: "HbA1c",
    price: 350,
    priceBefore: 700,
    type: "popularTests",
  },
  {
    id: 5,
    title: "Complete Health Package",
    noOfTest: "Includes 65 test",
    price: 2500,
    priceBefore: 5000,
    type: "healthPackage",
  },
  {
    id: 6,
    title: "Women Health Package",
    noOfTest: "Includes 65 test",
    price: 2500,
    priceBefore: 5000,
    type: "healthPackage",
  },
  {
    id: 7,
    title: "Family Health Package",
    noOfTest: "Includes 65 test",
    price: 2500,
    priceBefore: 5000,
    type: "healthPackage",
  },
  {
    id: 8,
    title: "Advanced Health Package",
    noOfTest: "Includes 65 test",
    price: 2500,
    priceBefore: 5000,
    type: "healthPackage",
  },
  {
    id: 9,
    title: "HbA1c",
    price: 350,
    priceBefore: 700,
    type: "topBooked",
  },
  {
    id: 10,
    title: "Diabetes Screening",
    price: 350,
    priceBefore: 700,
    type: "topBooked",
  },
  {
    id: 11,
    title: "Glucose, Fasting ",
    price: 350,
    priceBefore: 700,
    type: "topBooked",
  },
  {
    id: 12,
    title: "Lipid Profile",
    price: 350,
    priceBefore: 700,
    type: "topBooked",
  },
];

export default cardData;
